travis:
  secure:
    BINSTAR_TOKEN: pkvnT5IjUQZbec3r3r0xRDrBqZuTQjR7wfVPM2lIz4pXM6YbzysHoLFwy1j8/o1civN7U/kTo3V+LofiU7h7iUSi8CLZWIhKiur4rJ7csnAb7KyM0BgcXAagWeEr+/+dDptNckAcdFrMJKpP38f7xNpM5yElHizB7CAfLxk2ThacZIcGEihb0SSpDOzZZNPYWzNJ0Vl4Sm4ccCWGV3naoF7hpDIpn3cnEn5JbGAiX1spch3NV74FkeirdpzKBJ3iyrXDft0yPBRfGcmx+vAVBYKE8Azi7/w+755QK3JjUvM0X7NT8ahSRavio3ohHuawbDvAbhK9jwHjQ5BA6pCqEgbF2LDXYuZoohnrD+x6da/5/SFGnDjO2XKvuvu/X8uFAdmeTrr4VTL9Ua0R5odmmJ4nDyn8LdQ7leldNOOpZEwxQW/RLkjveBeFuJkbrsxu/y8U7EDuc4NMG/CpPMAmAJQyXWLknXi7UzHwKehRmQXUMZHoD6lAauBkKVWT8D3rziosiS/mIK1KSCLjN7NJ8EqlFgtBb8M4gfbitqRklSQH77X+0Q85jYqNfD2DN2HUXJN6dbSxwnsCXI7lDdS+G8QS+LeL9WdISxuVC/y6WsCXYdJBgtVNd7Zw/OcEGy+h3DaHqfNr3WRj53eDj3S9Qd2E/tfwCeFEn5+yg0gH7T0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
